services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/:app/src
      - ./db/:app/db
      - ./config/:app/config
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: