name: Build docker image

on:
  workflow_run:
    workflows: ["Basic tests"]
    types:
      - completed
    status: success
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and test img
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.event.pull_request.number || github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Push img
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
