name: Basic test

on:
  push:
    branches:
      - main
      - data_processing_api
    pull_request:
      branches:
        - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python Set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dep
        run:
          python -m pip install --upgrade pip && pip install -r requirements.txt
        working-directory: ./

      - name: Run tests
        run: python base_test.py
        working-directory: ./src/

      - name: Test failed
        if: failure()
        run: |
          echo "Fail"

      - name: Test success
        if: success()
        run: |
          echo "Success"