name: Basic tests

on:
  push:
    branches:
      - main
      - data_processing_api
    pull_request:
      branches:
        - main


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd="redis-server --version" --health-interval=5s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python Set up
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dep
        run: |
          python -m pip install --upgrade pip && \
          pip install -r requirements.txt && \
          pip install pylint
        working-directory: ./

      - name: List Python files
        run: find ./src -name "*.py"

      - name: Lint with PyLint
        run: pylint $(git ls-files '*.py') --output=pylint.txt || true

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: pylint
          path: pylint.txt
          retention-days: 1

      - name: Run tests
        run: python base_test.py
        working-directory: ./src/

      - name: Test failed
        if: failure()
        run: |
          echo "Fail"

      - name: Test success
        if: success()
        run: |
          echo "Success"